### ISSUE TITLE
Error after running follow_wall.py 

### ISSUE THREAD

**Issue by taletovic** [ssscassio/ros-wall-follower-2-wheeled-robot#1]
Hello,

on the first run I got a Syntax Error because of the comma, line 130 in **follow_wall.py**.
After removing that comma I've been able to run the command:
`rosrun two-wheeled-robot-motion-planning follow_wall.py`

But after running the command the robot starts to move a bit but in the wrong direction, something like this:

![Screenshot from 2019-05-24 10-15-15](https://user-images.githubusercontent.com/50860059/58312988-d765ef80-7e0c-11e9-8d1d-e84820b45d9b.png)

In the Terminal I am getting the following error:
```
[ERROR] [1558685343.579782, 979.289000]: bad callback: <function clbk_laser at 0x7fc92b71de60>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/myws/src/two-wheeled-robot-motion-planning/scripts/follow_wall.py", line 95, in clbk_laser
    'left':   min(min(msg.ranges[720:863]), inf),
ValueError: min() arg is an empty sequence

[ERROR] [1558685343.639372, 979.343000]: bad callback: <function clbk_laser at 0x7fc92b71de60>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/myws/src/two-wheeled-robot-motion-planning/scripts/follow_wall.py", line 95, in clbk_laser
    'left':   min(min(msg.ranges[720:863]), inf),
ValueError: min() arg is an empty sequence

[ERROR] [1558685343.690462, 979.378000]: bad callback: <function clbk_laser at 0x7fc92b71de60>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/myws/src/two-wheeled-robot-motion-planning/scripts/follow_wall.py", line 95, in clbk_laser
    'left':   min(min(msg.ranges[720:863]), inf),
ValueError: min() arg is an empty sequence

[ERROR] [1558685343.754236, 979.431000]: bad callback: <function clbk_laser at 0x7fc92b71de60>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/myws/src/two-wheeled-robot-motion-planning/scripts/follow_wall.py", line 95, in clbk_laser
    'left':   min(min(msg.ranges[720:863]), inf),
ValueError: min() arg is an empty sequence

[ERROR] [1558685343.813002, 979.474000]: bad callback: <function clbk_laser at 0x7fc92b71de60>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/myws/src/two-wheeled-robot-motion-planning/scripts/follow_wall.py", line 95, in clbk_laser
    'left':   min(min(msg.ranges[720:863]), inf),
ValueError: min() arg is an empty sequence
```
I am using Ubuntu 16.04 with:
```
PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_sim_time: True
```
Could you please help me to resolve the problem? Thanks in advance.

**Comment by ssscassio** [comment]
@taletovic 
Thanks for the advice about line 130.
It seems that you are not getting the laser sensors message right.
Can you launch the robot at the world and check the messages that are being sent?

First run ```rostopic list``` and check if there is a **/m2wr/laser/scan** topic.
After that, run ```rostopic echo /m2wr/laser/scan``` and check if you are getting any response.

**Comment by taletovic** [comment]
@ssscassio Hello,
you're welcome.

After some research I found the error in the code.
In this part of the **ros-wall-follower-2-wheeled-robot/catkin_ws/src/two-wheeled-robot-motion-planning/scripts/follow_wall.py** code:
```

    # Determination of minimum distances in each region
    regions_ = {
        'bright':  min(min(msg.ranges[0:143]), inf),
        'right': min(min(msg.ranges[144:287]), inf),
        'fright':  min(min(msg.ranges[288:431]), inf),
        'front':  min(min(msg.ranges[432:575]), inf),
        'fleft':   min(min(msg.ranges[576:719]), inf),
        'left':   min(min(msg.ranges[720:863]), inf),
        'bleft':   min(min(msg.ranges[864:1007]), inf),
    }
```
You are dividing the samples taken from the `/scan` in 7 regions (bright, right, ...) but you are parsing the message from the `/scan` topic to the index of 1007 which you don't have by your sensor.
If you open the xacro file **ros-wall-follower-2-wheeled-robot/simulation_ws/src/two-wheeled-robot-simulation/m2wr_description/urdf/gazebo.xacro** and look into this part of the code:

```
<sensor type="ray" name="head_hokuyo_sensor">
    <pose>0 0 0 0 0 0</pose>
    <visualize>false</visualize>
    <update_rate>20</update_rate>
    <ray>
    <scan>
        <horizontal>
        <samples>720</samples>
        <resolution>1</resolution>
        <min_angle>-1.570796</min_angle>
        <max_angle>1.570796</max_angle>
        </horizontal>
    </scan>
    <range>
        <min>0.10</min>
        <max>10.0</max>
        <resolution>0.01</resolution>
    </range>
    <noise>
        <type>gaussian</type>
        <mean>0.0</mean>
        <stddev>0.01</stddev>
    </noise>
    </ray>
    <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
    <topicName>/m2wr/laser/scan</topicName>
    <frameName>sensor_laser</frameName>
    </plugin>
</sensor>
```
We can see:

`<samples>720</samples>`
 
that the sensor outputs only 720 samples of data and not 1007 like in your python code.
So you can edit the python code and divide the regions from 0 to 720 or change the amount of samples in the xacro code. Your call.
